services:
  - type: web
    name: quest-api
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python start_production.py
    envVars:
      - key: SUPABASE_URL
        value: your_supabase_project_url
      - key: SUPABASE_ANON_KEY
        value: your_supabase_anon_key
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: your_supabase_service_role_key
      - key: API_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://yourdomain.com
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id.apps.googleusercontent.com
      - key: GOOGLE_REDIRECT_URI
        value: https://your-app-name.onrender.com/api/v1/auth/google/callback
      # 注意：GOOGLE_CLIENT_SECRET 应该通过 Render Dashboard 手动配置以确保安全
      # OpenAI API 配置 - 需要在 Render Dashboard 中设置实际值
      - key: SUMMARY_ENABLED
        value: true
      - key: SUMMARY_PROVIDER
        value: openai
      - key: SUMMARY_MODEL
        value: gpt-4o-mini
      - key: SUMMARY_MAX_TOKENS
        value: 1200
      - key: SUMMARY_INPUT_CHAR_LIMIT
        value: 16000
      - key: SUMMARY_CHUNK_CHAR_LIMIT
        value: 4000
      - key: SUMMARY_MAX_CHUNKS
        value: 8
      - key: SUMMARY_TEMPERATURE
        value: 0.3
      - key: SUMMARY_INPUT_TOKEN_LIMIT
        value: 6000
      # OPENAI_API_KEY 和 OPENAI_BASE_URL 需要在 Render Dashboard 中手动配置
      # Curator 配置已移除 - Trafilatura 更强大
      # Sumy 配置已移除 - 直接使用 Trafilatura
      - key: PAGE_TEXT_MAX_LEN
        value: 500000
      # Trafilatura 正文提取配置 - 调整为更宽松的提取策略
      - key: TRAFILATURA_ENABLED
        value: true
      - key: TRAFILATURA_INCLUDE_COMMENTS
        value: false
      - key: TRAFILATURA_INCLUDE_TABLES
        value: true
      - key: TRAFILATURA_INCLUDE_FORMATTING
        value: false
      - key: TRAFILATURA_DEDUPLICATE
        value: false  # 禁用去重，保留更多内容
      - key: TRAFILATURA_FAVOR_PRECISION
        value: false  # 不优先精确度，避免过度过滤
      - key: TRAFILATURA_FAVOR_RECALL
        value: true   # 优先召回率，保留更多内容
      # TF-IDF 预处理优化配置 - 调整为更宽松的参数以避免过度过滤
      - key: TFIDF_OPTIMIZER_ENABLED
        value: true
      - key: TFIDF_MIN_TEXT_LENGTH
        value: 50  # 降低最小文本长度要求
      - key: TFIDF_MAX_FEATURES
        value: 10000
      - key: TFIDF_MIN_DF
        value: 1  # 降低最小文档频率，保留更多内容
      - key: TFIDF_MAX_DF
        value: 0.9  # 提高最大文档频率，保留更多内容
      - key: TFIDF_SCORE_FLOOR
        value: 0.04  # 适中的得分下限，保持质量控制
      - key: TFIDF_CONTENT_RATIO
        value: 0.5   # 适中的内容比例，保留50%的内容
      - key: TFIDF_MIN_KEEP_K
        value: 60    # 适中的最少保留块数
      - key: TFIDF_PERCENTILE_THRESHOLD
        value: 0.70  # 适中的分位阈值，保持质量控制
      - key: TFIDF_REMOVE_LOW_QUALITY
        value: true   # 开启低质量过滤，保持适度质量控制
      - key: TFIDF_ENHANCE_BLOCKS
        value: true
      - key: TFIDF_ENABLE_CHINESE_SEG
        value: true
      - key: TFIDF_MAX_LINK_DENSITY
        value: 0.4  # 适中的链接密度阈值
      - key: TFIDF_MIN_ALPHANUMERIC_RATIO
        value: 0.4  # 适中的字母数字比例要求
      # 文本分块器配置 - 优化为RAG最佳实践 (500-1000 tokens)
      - key: CHUNKER_ENABLED
        value: false
      - key: CHUNKER_CHUNK_SIZE
        value: 2000  # 字符数，约500-750 tokens (1 token ≈ 2.5-4 字符)
      - key: CHUNKER_CHUNK_OVERLAP
        value: 400   # 增加重叠以保持语义连续性
      - key: CHUNKER_MAX_TOKENS
        value: 1000  # 限制最大token数，符合RAG最佳实践
      - key: CHUNKER_METHOD
        value: recursive
      # 数据库表配置
      - key: ENABLE_INSIGHT_CHUNKS
        value: true
      # OpenAI Embedding 配置
      - key: EMBEDDING_ENABLED
        value: false
      - key: OPENAI_API_KEY
        value: your_openai_api_key
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: OPENAI_EMBEDDING_DIMENSIONS
        value: 1536
      - key: OPENAI_EMBEDDING_BATCH_SIZE
        value: 100
      - key: OPENAI_EMBEDDING_MAX_RETRIES
        value: 3
      - key: OPENAI_EMBEDDING_TIMEOUT
        value: 30
      # AI聊天配置
      - key: CHAT_MODEL
        value: gpt-4o-mini
      - key: CHAT_MAX_TOKENS
        value: 2000
      - key: CHAT_TEMPERATURE
        value: 0.3
      - key: CHAT_DEFAULT_STREAM
        value: true
      # RAG配置
      - key: RAG_ENABLED
        value: true
      - key: RAG_DEFAULT_K
        value: 6
      - key: RAG_DEFAULT_MIN_SCORE
        value: 0.2
      - key: RAG_MAX_CONTEXT_TOKENS
        value: 2000
      # 限流配置
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 30
      # 性能优化配置
      - key: MAX_INSIGHTS_LIMIT
        value: 1000
      - key: ENABLE_GZIP_COMPRESSION
        value: true
      - key: QUERY_CACHE_TTL
        value: 30
      - key: BATCH_SIZE_LIMIT
        value: 200
    autoDeploy: true
    branch: main
