services:
  - type: web
    name: quest-api
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python start_production.py
    envVars:
      - key: SUPABASE_URL
        value: your_supabase_project_url
      - key: SUPABASE_ANON_KEY
        value: your_supabase_anon_key
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: your_supabase_service_role_key
      - key: API_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://yourdomain.com
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id.apps.googleusercontent.com
      - key: GOOGLE_REDIRECT_URI
        value: https://your-app-name.onrender.com/api/v1/auth/google/callback
      # 注意：GOOGLE_CLIENT_SECRET 应该通过 Render Dashboard 手动配置以确保安全
      # OpenAI API 配置 - 需要在 Render Dashboard 中设置实际值
      - key: SUMMARY_ENABLED
        value: true
      - key: SUMMARY_PROVIDER
        value: openai
      - key: SUMMARY_MODEL
        value: gpt-4o-mini
      - key: SUMMARY_MAX_TOKENS
        value: 1200
      - key: SUMMARY_INPUT_CHAR_LIMIT
        value: 16000
      - key: SUMMARY_CHUNK_CHAR_LIMIT
        value: 4000
      - key: SUMMARY_MAX_CHUNKS
        value: 8
      - key: SUMMARY_TEMPERATURE
        value: 0.3
      # OPENAI_API_KEY 和 OPENAI_BASE_URL 需要在 Render Dashboard 中手动配置
      # Curator 配置已移除 - Trafilatura 更强大
      # Sumy 预处理配置
      - key: SUMY_PREPROCESSING_ENABLED
        value: true
      - key: SUMY_ALGORITHM
        value: lexrank
      - key: SUMY_TOP_K_PARAGRAPHS
        value: 4
      - key: SUMY_MAX_SENTENCES
        value: 10
      - key: SUMY_PRESERVE_MODE
        value: balanced
      - key: SUMY_PRESERVE_RATIO
        value: 0.5
      - key: SUMY_FALLBACK_MAX_LENGTH
        value: 100000
      - key: PAGE_TEXT_MAX_LEN
        value: 500000
      - key: NLTK_DATA
        value: /opt/render/nltk_data
      # Trafilatura 正文提取配置
      - key: TRAFILATURA_ENABLED
        value: true
      - key: TRAFILATURA_INCLUDE_COMMENTS
        value: false
      - key: TRAFILATURA_INCLUDE_TABLES
        value: true
      - key: TRAFILATURA_INCLUDE_FORMATTING
        value: false
      - key: TRAFILATURA_DEDUPLICATE
        value: true
      - key: TRAFILATURA_FAVOR_PRECISION
        value: true
      - key: TRAFILATURA_FAVOR_RECALL
        value: false
      # 性能优化配置
      - key: MAX_INSIGHTS_LIMIT
        value: 1000
      - key: ENABLE_GZIP_COMPRESSION
        value: true
      - key: QUERY_CACHE_TTL
        value: 30
      - key: BATCH_SIZE_LIMIT
        value: 200
    autoDeploy: true
    branch: main
