services:
  - type: web
    name: quest-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_production.py
    envVars:
      - key: SUPABASE_URL
        value: your_supabase_project_url
      - key: SUPABASE_ANON_KEY
        value: your_supabase_anon_key
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: your_supabase_service_role_key
      - key: API_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://yourdomain.com
    autoDeploy: true
    branch: main
